



#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# List of all CSS transforms and their arguments
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
transform_info <- list(
  list(name = "matrix"      , units=NULL , args = letters[1:6]),
  list(name = "matrix3d"    , units=NULL , args = letters[1:16]),
  list(name = "none"        , units=NULL , args = c()),
  list(name = "perspective" , units=NULL , args = 'd'),
  list(name = "rotate"      , units='deg', args = c('angle')),
  list(name = "rotate3d"    , units='deg', args = c('x', 'y', 'z', 'angle')),
  list(name = "rotateX"     , units='deg', args = c('angle')),
  list(name = "rotateY"     , units='deg', args = c('angle')),
  list(name = "rotateZ"     , units='deg', args = c('angle')),
  list(name = "scale"       , units=NULL , args = c('x', 'y')),
  list(name = "scale3d"     , units=NULL , args = c('x', 'y', 'z')),
  list(name = "scaleX"      , units=NULL , args = c('x')),
  list(name = "scaleY"      , units=NULL , args = c('y')),
  list(name = "scaleZ"      , units=NULL , args = c('z')),
  list(name = "skew"        , units='deg', args = c('x', 'y')),
  list(name = "skewX"       , units='deg', args = c('x')),
  list(name = "skewY"       , units='deg', args = c('y')),
  list(name = "translate"   , units='px' , args = c('x', 'y')),
  list(name = "translate3d" , units='px' , args = c('x', 'y', 'z')),
  list(name = "translateX"  , units='px' , args = c('x')),
  list(name = "translateY"  , units='px' , args = c('y')),
  list(name = "translateZ"  , units='px' , args = c('z'))
)



# This is list of CSS properties.
# Sourced from the Adobe 'brackets' project
# https://github.com/adobe/brackets/blob/master/src/extensions/default/CSSCodeHints/CSSProperties.json

properties <- list(
  list(name = "align-content"             , values = c("center", "flex-end", "flex-start", "space-around", "space-between", "stretch")),
  list(name = "align-items"               , values = c("baseline", "center", "flex-end", "flex-start", "stretch")),
  list(name = "align-self"                , values = c("auto", "baseline", "center", "flex-end", "flex-start", "stretch")),
  list(name = "all"                       , values = c()),
  list(name = "animation"                 , values = c()),
  list(name = "animation-delay"           , values = c()),
  list(name = "animation-direction"       , values = c("alternate", "alternate-reverse", "normal", "reverse")),
  list(name = "animation-duration"        , values = c()),
  list(name = "animation-fill-mode"       , values = c("backwards", "both", "forwards", "none")),
  list(name = "animation-iteration-count" , values = "infinite"),
  list(name = "animation-name"            , values = "none"),
  list(name = "animation-play-state"      , values = c("paused", "running")),
  list(name = "animation-timing-function" , values = c("cubic-bezier()", "ease", "ease-in", "ease-in-out", "ease-out", "linear", "step-end", "step-start", "steps()")),
  list(name = "backface-visibility"       , values = c("hidden", "visible")),
  list(name = "background"                , values = c()),
  list(name = "background-attachment"     , values = c("fixed", "local", "scroll", "inherit")),
  list(name = "background-blend-mode"     , values = c("color", "color-burn", "color-dodge", "darken", "difference", "exclusion", "hard-light", "hue", "lighten", "luminosity", "multiply", "normal", "overlay", "saturation", "screen", "soft-light")),
  list(name = "background-clip"           , values = c("border-box", "content-box", "padding-box", "inherit")),
  list(name = "background-color"          , values = "inherit"),
  list(name = "background-image"          , values = c("image()", "linear-gradient()", "radial-gradient()", "repeating-linear-gradient()", "repeating-radial-gradient()", "url()")),
  list(name = "background-origin"         , values = c("border-box", "content-box", "padding-box", "inherit")),
  list(name = "background-position"       , values = c("left", "center", "right", "bottom", "top")),
  list(name = "background-repeat"         , values = c("no-repeat", "repeat", "repeat-x", "repeat-y", "round", "space")),
  list(name = "background-size"           , values = c("auto", "contain", "cover")),
  list(name = "border"                    , values = c()),
  list(name = "border-collapse"           , values = c("collapse", "separate", "inherit")),
  list(name = "border-color"              , values = "inherit"),
  list(name = "border-spacing"            , values = "inherit"),
  list(name = "border-style"              , values = c("dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge", "solid", "inherit")),
  list(name = "border-bottom"             , values = c()),
  list(name = "border-bottom-color"       , values = "inherit"),
  list(name = "border-bottom-left-radius" , values = c()),
  list(name = "border-bottom-right-radius", values = c()),
  list(name = "border-bottom-style"       , values = c("dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge", "solid", "inherit")),
  list(name = "border-bottom-width"       , values = c("medium", "thin", "thick", "inherit")),
  list(name = "border-image"              , values = "url()"),
  list(name = "border-image-outset"       , values = c()),
  list(name = "border-image-slice"        , values = c()),
  list(name = "border-image-source"       , values = c()),
  list(name = "border-image-repeat"       , values = c("repeat", "round", "space", "stretch")),
  list(name = "border-image-width"        , values = "auto"),
  list(name = "border-left"               , values = c()),
  list(name = "border-left-color"         , values = "inherit"),
  list(name = "border-left-style"         , values = c("dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge", "solid", "inherit")),
  list(name = "border-left-width"         , values = c("medium", "thin", "thick", "inherit")),
  list(name = "border-radius"             , values = c()),
  list(name = "border-right"              , values = c()),
  list(name = "border-right-color"        , values = "inherit"),
  list(name = "border-right-style"        , values = c("dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge", "solid", "inherit")),
  list(name = "border-right-width"        , values = c("medium", "thin", "thick", "inherit")),
  list(name = "border-top"                , values = c()),
  list(name = "border-top-color"          , values = "inherit"),
  list(name = "border-top-left-radius"    , values = c()),
  list(name = "border-top-right-radius"   , values = c()),
  list(name = "border-top-style"          , values = c("dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge", "solid", "inherit")),
  list(name = "border-top-width"          , values = c("medium", "thin", "thick", "inherit")),
  list(name = "border-width"              , values = c("medium", "thin", "thick", "inherit")),
  list(name = "box-decoration-break"      , values = c("clone", "slice")),
  list(name = "box-shadow"                , values = c()),
  list(name = "box-sizing"                , values = c("border-box", "content-box", "inherit")),
  list(name = "bottom"                    , values = c("auto", "inherit")),
  list(name = "break-after"               , values = c("always", "auto", "avoid", "avoid-column", "avoid-page", "avoid-region", "column", "left", "page", "region", "right")),
  list(name = "break-before"              , values = c("always", "auto", "avoid", "avoid-column", "avoid-page", "avoid-region", "column", "left", "page", "region", "right")),
  list(name = "break-inside"              , values = c("auto", "avoid", "avoid-column", "avoid-page", "avoid-region")),
  list(name = "caption-side"              , values = c("bottom", "top", "inherit")),
  list(name = "caret-color"               , values = "auto"),
  list(name = "clear"                     , values = c("both", "left", "none", "right", "inherit")),
  list(name = "clip"                      , values = c("auto", "inherit")),
  list(name = "color"                     , values = "inherit"),
  list(name = "columns"                   , values = c()),
  list(name = "column-count"              , values = c()),
  list(name = "column-fill"               , values = c("auto", "balance")),
  list(name = "column-gap"                , values = "normal"),
  list(name = "column-rule"               , values = c()),
  list(name = "column-rule-color"         , values = c()),
  list(name = "column-rule-style"         , values = c("dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge", "solid", "inherit")),
  list(name = "column-rule-width"         , values = c("medium", "thin", "thick", "inherit")),
  list(name = "column-span"               , values = c("all", "none")),
  list(name = "column-width"              , values = c("auto", "inherit")),
  list(name = "content"                   , values = c("attr()", "close-quote", "no-close-quote", "no-open-quote", "normal", "none", "open-quote", "inherit")),
  list(name = "counter-increment"         , values = c("none", "inherit")),
  list(name = "counter-reset"             , values = c("none", "inherit")),
  list(name = "cursor"                    , values = c("alias", "all-scroll", "auto", "cell", "col-resize", "context-menu", "copy", "crosshair", "default", "e-resize", "ew-resize", "grab", "grabbing", "help", "inherit", "move", "n-resize", "ne-resize", "nesw-resize", "no-drop", "none", "not-allowed", "ns-resize", "nw-resize", "nwse-resize", "pointer", "progress", "row-resize", "s-resize", "se-resize", "sw-resize", "text", "vertical-text", "w-resize", "wait", "zoom-in", "zoom-out")),
  list(name = "direction"                 , values = c("ltr", "rtl", "inherit")),
  list(name = "display"                   , values = c("block", "contents", "flex", "flow-root", "grid", "inline", "inline-block", "inline-flex", "inline-grid", "inline-table", "list-item", "none", "run-in", "subgrid", "table", "table-caption", "table-cell", "table-column", "table-column-group", "table-footer-group", "table-header-group", "table-row", "table-row-group", "inherit")),
  list(name = "empty-cells"               , values = c("hide", "show", "inherit")),
  list(name = "filter"                    , values = c("blur()", "brightness()", "contrast()", "custom()", "drop-shadow()", "grayscale()", "hue-rotate()", "invert()", "none", "opacity()", "sepia()", "saturate()", "url()")),
  list(name = "flex"                      , values = c("auto", "initial", "none")),
  list(name = "flex-basis"                , values = "auto"),
  list(name = "flex-direction"            , values = c("column", "column-reverse", "row", "row-reverse")),
  list(name = "flex-flow"                 , values = c("column", "column-reverse", "nowrap", "row", "row-reverse", "wrap", "wrap-reverse")),
  list(name = "flex-grow"                 , values = c()),
  list(name = "flex-shrink"               , values = c()),
  list(name = "flex-wrap"                 , values = c("nowrap", "wrap", "wrap-reverse")),
  list(name = "float"                     , values = c("left", "right", "none", "inherit")),
  list(name = "flow-into"                 , values = "none"),
  list(name = "flow-from"                 , values = c("none", "inherit")),
  list(name = "font"                      , values = c()),
  list(name = "font-display"              , values = c("auto", "block", "swap", "fallback", "optional")),
  list(name = "font-family"               , values = c("cursive", "fantasy", "inherit", "monospace", "sans-serif", "serif")),
  list(name = "font-feature-settings"     , values = "normal"),
  list(name = "font-kerning"              , values = c("auto", "none", "normal")),
  list(name = "font-language-override"    , values = "normal"),
  list(name = "font-size"                 , values = c()),
  list(name = "font-size-adjust"          , values = c("auto", "none")),
  list(name = "font-stretch"              , values = c("condensed", "expanded", "extra-condensed", "extra-expanded", "normal", "semi-condensed", "semi-expanded", "ultra-condensed", "ultra-expanded")),
  list(name = "font-style"                , values = c("italic", "normal", "oblique")),
  list(name = "font-synthesis"            , values = c("none", "style", "weight")),
  list(name = "font-variant"              , values = c("normal", "small-caps", "inherit")),
  list(name = "font-variant-alternates"   , values = "normal"),
  list(name = "font-variant-caps"         , values = c("normal", "small-caps", "all-small-caps", "petite-caps", "all-petite-caps", "unicase", "titling-caps")),
  list(name = "font-variant-east-asian"   , values = "normal"),
  list(name = "font-variant-ligatures"    , values = c("normal", "none")),
  list(name = "font-variant-numeric"      , values = "normal"),
  list(name = "font-variant-position"     , values = c("normal", "sub", "super")),
  list(name = "font-weight"               , values = c("bold", "bolder", "lighter", "normal", "100", "200", "300", "400", "500", "600", "700", "800", "900", "inherit")),
  list(name = "grid"                      , values = c()),
  list(name = "grid-area"                 , values = c()),
  list(name = "grid-auto-columns"         , values = c()),
  list(name = "grid-auto-flow"            , values = c("row", "column", "dense")),
  list(name = "grid-auto-rows"            , values = c()),
  list(name = "grid-column"               , values = "auto"),
  list(name = "grid-column-end"           , values = c()),
  list(name = "grid-column-gap"           , values = c()),
  list(name = "grid-column-start"         , values = c()),
  list(name = "grid-gap"                  , values = c()),
  list(name = "grid-row"                  , values = "auto"),
  list(name = "grid-row-end"              , values = c()),
  list(name = "grid-row-start"            , values = c()),
  list(name = "grid-row-gap"              , values = c()),
  list(name = "grid-template"             , values = "none"),
  list(name = "grid-template-areas"       , values = c()),
  list(name = "grid-template-columns"     , values = "auto"),
  list(name = "grid-template-rows"        , values = "auto"),
  list(name = "hanging-punctuation"       , values = c("allow-end", "first", "force-end", "last", "none")),
  list(name = "height"                    , values = c("auto", "inherit")),
  list(name = "hyphens"                   , values = c("auto", "manual", "none")),
  list(name = "image-orientation"         , values = c()),
  list(name = "image-resolution"          , values = c("from-image", "snap")),
  list(name = "isolation"                 , values = c("auto", "isolate")),
  list(name = "justify-content"           , values = c("center", "flex-end", "flex-start", "space-around", "space-between")),
  list(name = "left"                      , values = c("auto", "inherit")),
  list(name = "letter-spacing"            , values = c("normal", "inherit")),
  list(name = "line-height"               , values = c("normal", "inherit")),
  list(name = "list-style"                , values = c("none", "inherit", "initial", "unset", "url()", "armenian", "circle", "decimal", "decimal-leading-zero", "disc", "georgian", "inside", "lower-alpha", "lower-greek", "lower-latin", "lower-roman", "outside", "square", "upper-alpha", "upper-latin", "upper-roman")),
  list(name = "list-style-image"          , values = c("none", "url()", "inherit")),
  list(name = "list-style-position"       , values = c("inside", "outside", "inherit")),
  list(name = "list-style-type"           , values = c("armenian", "circle", "decimal", "decimal-leading-zero", "disc", "georgian", "lower-alpha", "lower-greek", "lower-latin", "lower-roman", "none", "square", "upper-alpha", "upper-latin", "upper-roman", "inherit")),
  list(name = "margin"                    , values = c("auto", "inherit")),
  list(name = "margin-bottom"             , values = c("auto", "inherit")),
  list(name = "margin-left"               , values = c("auto", "inherit")),
  list(name = "margin-right"              , values = c("auto", "inherit")),
  list(name = "margin-top"                , values = c("auto", "inherit")),
  list(name = "max-height"                , values = c("none", "inherit")),
  list(name = "max-width"                 , values = c("none", "inherit")),
  list(name = "min-height"                , values = "inherit"),
  list(name = "min-width"                 , values = "inherit"),
  list(name = "mix-blend-mode"            , values = c("color", "color-burn", "color-dodge", "darken", "difference", "exclusion", "hard-light", "hue", "lighten", "luminosity", "multiply", "normal", "overlay", "saturation", "screen", "soft-light")),
  list(name = "object-fit"                , values = c("contain", "cover", "fill", "none", "scale-down")),
  list(name = "object-position"           , values = c("left", "center", "right", "bottom", "top")),
  list(name = "opacity"                   , values = "inherit"),
  list(name = "order"                     , values = c()),
  list(name = "orphans"                   , values = "inherit"),
  list(name = "outline"                   , values = "inherit"),
  list(name = "outline-color"             , values = c("invert", "inherit")),
  list(name = "outline-offset"            , values = "inherit"),
  list(name = "outline-style"             , values = c("dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge", "solid", "inherit")),
  list(name = "outline-width"             , values = c("medium", "thin", "thick", "inherit")),
  list(name = "overflow"                  , values = c("auto", "hidden", "scroll", "visible", "inherit")),
  list(name = "overflow-x"                , values = c("auto", "hidden", "scroll", "visible", "inherit")),
  list(name = "overflow-y"                , values = c("auto", "hidden", "scroll", "visible", "inherit")),
  list(name = "padding"                   , values = "inherit"),
  list(name = "padding-bottom"            , values = c()),
  list(name = "padding-left"              , values = c()),
  list(name = "padding-right"             , values = c()),
  list(name = "padding-top"               , values = c()),
  list(name = "page-break-after"          , values = c("always", "auto", "avoid", "left", "right", "inherit")),
  list(name = "page-break-before"         , values = c("always", "auto", "avoid", "left", "right", "inherit")),
  list(name = "page-break-inside"         , values = c("auto", "avoid", "inherit")),
  list(name = "perspective"               , values = "none"),
  list(name = "perspective-origin"        , values = c("bottom", "center", "left", "right", "top")),
  list(name = "pointer-events"            , values = c("all", "auto", "fill", "inherit", "none", "painted", "stroke", "visible", "visibleFill", "visiblePainted", "visibleStroke")),
  list(name = "position"                  , values = c("absolute", "fixed", "relative", "static", "sticky", "inherit")),
  list(name = "quotes"                    , values = c("none", "inherit")),
  list(name = "region-break-after"        , values = c("always", "auto", "avoid", "avoid-column", "avoid-page", "avoid-region", "column", "left", "page", "region", "right")),
  list(name = "region-break-before"       , values = c("always", "auto", "avoid", "avoid-column", "avoid-page", "avoid-region", "column", "left", "page", "region", "right")),
  list(name = "region-break-inside"       , values = c("auto", "avoid", "avoid-column", "avoid-page", "avoid-region")),
  list(name = "region-fragment"           , values = c("auto", "break")),
  list(name = "resize"                    , values = c("both", "horizontal", "none", "vertical", "inherit")),
  list(name = "right"                     , values = c("auto", "inherit")),
  list(name = "scroll-behavior"           , values = c("auto", "smooth")),
  list(name = "src"                       , values = "url()"),
  list(name = "shape-image-threshold"     , values = c()),
  list(name = "shape-inside"              , values = c("auto", "circle()", "ellipse()", "inherit", "outside-shape", "polygon()", "rectangle()")),
  list(name = "shape-margin"              , values = c()),
  list(name = "shape-outside"             , values = c("none", "inherit", "circle()", "ellipse()", "polygon()", "inset()", "margin-box", "border-box", "padding-box", "content-box", "url()", "image()", "linear-gradient()", "radial-gradient()", "repeating-linear-gradient()", "repeating-radial-gradient()")),
  list(name = "tab-size"                  , values = c()),
  list(name = "table-layout"              , values = c("auto", "fixed", "inherit")),
  list(name = "text-align"                , values = c("start", "end", "center", "left", "justify", "right", "match-parent", "justify-all", "inherit")),
  list(name = "text-align-last"           , values = c("center", "left", "justify", "right", "inherit")),
  list(name = "text-decoration"           , values = c("line-through", "none", "overline", "underline", "inherit")),
  list(name = "text-decoration-color"     , values = c()),
  list(name = "text-decoration-line"      , values = c("line-through", "none", "overline", "underline")),
  list(name = "text-decoration-skip"      , values = c("edges", "ink", "none", "objects", "spaces")),
  list(name = "text-decoration-style"     , values = c("dashed", "dotted", "double", "solid", "wavy")),
  list(name = "text-emphasis"             , values = c()),
  list(name = "text-emphasis-color"       , values = c()),
  list(name = "text-emphasis-position"    , values = c("above", "below", "left", "right")),
  list(name = "text-emphasis-style"       , values = c("circle", "dot", "double-circle", "filled", "none", "open", "sesame", "triangle")),
  list(name = "text-indent"               , values = "inherit"),
  list(name = "text-justify"              , values = c("auto", "none", "inter-word", "inter-character", "inherit")),
  list(name = "text-overflow"             , values = c("clip", "ellipsis", "inherit")),
  list(name = "text-shadow"               , values = c()),
  list(name = "text-rendering"            , values = c("auto", "geometricPrecision", "optimizeLegibility", "optimizeSpeed")),
  list(name = "text-transform"            , values = c("capitalize", "full-width", "lowercase", "none", "uppercase", "inherit")),
  list(name = "text-underline-position"   , values = c("alphabetic", "auto", "below", "left", "right")),
  list(name = "top"                       , values = c("auto", "inherit")),
  list(name = "transform"                 , values = c("matrix()", "matrix3d()", "none", "perspective()", "rotate()", "rotate3d()", "rotateX()", "rotateY()", "rotateZ()", "scale()", "scale3d()", "scaleX()", "scaleY()", "scaleZ()", "skewX()", "skewY()", "translate()", "translate3d()", "translateX()", "translateY()", "translateZ()")),
  list(name = "transform-origin"          , values = c("bottom", "center", "left", "right", "top")),
  list(name = "transform-style"           , values = c("flat", "preserve-3d")),
  list(name = "transition"                , values = c()),
  list(name = "transition-delay"          , values = c()),
  list(name = "transition-duration"       , values = c()),
  list(name = "transition-property"       , values = c("all", "none")),
  list(name = "transition-timing-function", values = c("cubic-bezier()", "ease", "ease-in", "ease-in-out", "ease-out", "linear", "step-end", "step-start", "steps()")),
  list(name = "unicode-bidi"              , values = c("bidi-override", "embed", "normal", "inherit")),
  list(name = "unicode-range"             , values = c()),
  list(name = "user-select"               , values = c("all", "auto", "contain", "none", "text")),
  list(name = "vertical-align"            , values = c("baseline", "bottom", "middle", "sub", "super", "text-bottom", "text-top", "top", "inherit")),
  list(name = "visibility"                , values = c("collapse", "hidden", "visible", "inherit")),
  list(name = "white-space"               , values = c("normal", "nowrap", "pre", "pre-line", "pre-wrap", "inherit")),
  list(name = "widows"                    , values = "inherit"),
  list(name = "width"                     , values = c("auto", "inherit")),
  list(name = "will-change"               , values = c("auto", "contents", "opacity", "scroll-position", "transform", "inherit", "initial", "unset")),
  list(name = "word-break"                , values = c("normal", "break-all", "keep-all")),
  list(name = "word-spacing"              , values = c("normal", "inherit")),
  list(name = "word-wrap"                 , values = c("break-word", "normal")),
  list(name = "z-index"                   , values = c("auto", "inherit"))
)
